# -*- coding: utf-8 -*-
"""113z29044_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCEqHBUBxAKFU-kl4i_JVyjjBSSkh2XX
"""

import math
#q1
i = 12
j = 3
print(10 < (i*2) or (j - 6) < (2**(-1)))
print(1 < (i%5) and i//4<j)
print(not i//7>j and i%2 == 0)

#q2
students = 4
apples = 25
student_apples = apples // students
leftover_apples = apples % students
print(student_apples)
print(leftover_apples)


#q3
annual_prof = 0.23 * proj_sales
proj_sales = 5000
print(annual_prof)