# -*- coding: utf-8 -*-
"""113Z29044_ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AebUSPt_EObY4II98NXBoIEDImXEpFnF
"""

#Q1
big = 'BIG LETTERS'
little = big.lower()
print(little)

str3 = 'Python language programming'
print(str3.count('g')) #total number of 'g' = 4
print(str3.find('p')) # 'p' index is 16

#Q2
first_name3 = input('first name:')
last_name3 = input('last name:')
last_id3 = input('ID number:')
username = (first_name3[0:3] + last_name3[0:3] + last_id3[-3:])
print(username)

#Q3
s1='HappyNewYear'
s2='happynewyear'
s3='new'
s4='birthday'
print(len(s1))
print(len(s1) == len(s2))
s1.find(s3) == True #there exists an instance of 'new' in 'HappyNewYear' --> this returns False --> no instance of 'new' in 'HappyNewYear'