# -*- coding: utf-8 -*-
"""113z29044_ex5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFWi1npeCDdsvnl6EzAbLdJJLCsZYycm
"""

#Q1
input_number = int(input("Input your number here:"))
if input_number == 1:
  print("I")
elif input_number == 2:
  print("II")
elif input_number == 3:
  print("III")
elif input_number == 4:
  print("IV")
elif input_number == 5:
  print("V")
elif input_number == 6:
  print("VI")
elif input_number == 7:
  print("VII")
elif input_number == 8:
  print("VIII")
elif input_number == 9:
  print("IX")
elif input_number == 10:
  print("X")
else:
    print("Error!")

#Q2
num_rows = int(input("How many rows do you want? (1-30)"))
# Check if the input is within the valid range
if 1 <= num_rows <= 30:
    for i in range(1, num_rows + 1):
        print(' ' * (num_rows - i) + '*' * (2 * i - 1))
else:
    print("Invalid input. Please enter a number between 1 and 30.")