# -*- coding: utf-8 -*-
"""113z29044_ex4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuTatmGqIXfkydHIhciQSENdQrDdIhzy
"""

#Q1
while True:
    side1 = int(input('Length of 1st side:'))
    side2 = int(input('Length of 2nd side:'))
    side3 = int(input('Length of 3rd side:'))
    if side1 + side2 > side3 and side2 + side3 > side1 and side1 + side3 > side2:
        print("OK for triangle construction!")
        break
    else:
        print("Unable to construct a triangle. Please try again")

#Q2
for num in range(0,5):
   print(' '*num+'#')
for num in range (3,-1,-1):
    print(' '*num+'#')

#Q3
total_number = 0
for num in range(-99, -1, 2):
    total_number += num
    num += -1
print(total_number)

#Q4
import random
rand_number = random.randint(0,99)
user_value = int(input("Please input a positive integer from 0-99:"))
while True:
    if user_value == rand_number:
        print("Congrats! You're correct!")
        break
    elif user_value < rand_number:
        print("The number you guessed is too small")
    else:
        print('The number you guessed is too big')
    #allow the user to input a new guess after the initial guess
    user_value = int(input("Please input a new positive integer from 0-99:"))

#Q5
numerator = range(1,31)
denominator = range(30, 0, -1)
total_sum = 0
for num, den in zip(numerator, denominator):
    total_sum += num / den
print("The sum is:", total_sum)