# -*- coding: utf-8 -*-
"""113Z29044_HW1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMhikF-8pPGOaMw0-CRUh0DGjrYj8J0H

# (1)	Textbook p201 (10)

Write a program that uses nested loops to draw this pattern:
* output:
~~~
##
# #
#  #
#   #
#    #
#     #
~~~
"""

num_rows = int(input("Enter the number of rows: "))
def main():
  for i in range(num_rows):
    print("#" + " " * i + "#")
main()

# 作答區(1)
#input rows from user
rows = int(input("Enter the number of rows: "))
def main():
  for i in range(rows):
    #width of each row is i + 2 (first # + spaces + second #)
    for j in range(i + 2):
      # print # at start/end of each row
        if j == 0 or j == i + 1:
            print("#", end="")
            # print spaces inbetween each #
        else:
            print(" ", end="")
    print()
main()

"""# (2)	Textbook p200 (4)

The distance a vehicle travels can be calculated as follows:
<center>distance = speed × time</center>

* For example, if a train travels 40 miles per hour for three hours, the distance traveled is 120 miles. Write a program that asks the user for the speed of a vehicle (in miles per hour) and the number of hours it has traveled. It should then use a loop to display the distance the vehicle has traveled for each hour of that time period. Here is an example of the desired output:
~~~
What is the speed of the vehicle in mph? 40
How many hours has it traveled? 3
Hour Distance_Traveled
1 40
2 80
3 120
~~~
"""

# 作答區(2)
speed = int(input("What is the speed of the vehicle in mph? "))
time = int(input("How many hours has it traveled? "))

for i in range(1, time + 1):
  dist_traveled = speed * i
  print(dist_traveled)

"""# (3)	Textbook p199 (4)

Write a loop that asks the user to enter a number. The loop should iterate 10 times and keep a running total of the numbers entered.
* For example:
~~~
Please enter a number: 1
Please enter a number: 2
Please enter a number: 3
Please enter a number: 1
Please enter a number: 3
Please enter a number: 4
Please enter a number: 2
Please enter a number: 1
Please enter a number: 4
Please enter a number: 1
The total of the above numbers: 22
~~~
"""

# 作答區(3)
i = 0
for i in range(10):
  user_input = int(input("Please input a number: "))
  i += user_input
print("The total of the above numbers: ", i)

"""# (4)	Textbook p154 (9)

The Fast Freight Shipping Company charges the following rates:

<table border="1">
  <tr>
    <th>Weight of Package</th>
    <th>Rate per Pound</th>
  </tr>
  <tr>
    <td>2 pounds or less</td>
    <td>$ 1.10</td>
  </tr>
  <tr>
    <td>Over 2 pounds but not more than 6 pounds</td>
    <td>$ 2.20</td>
  </tr>
  <tr>
    <td>Over 6 pounds but not more than 10 pounds</td>
    <td>$ 3.70</td>
  </tr>
  <tr>
    <td>Over 10 pounds</td>
    <td>$ 3.80</td>
  </tr>
</table>

Write a program that asks the user to enter the weight of a package and then displays the shipping charges.
* For example (1):
~~~
Please enter the weight of a package: 10
The shipping charges: $ 37.000000
~~~

* For example (2):
~~~
Please enter the weight of a package: 1.5
The shipping charges: $ 1.650000
~~~
"""

# 作答區(4)
user_input = float(input("Please enter the weight of your package: "))

if user_input <=0:
  print("Error: Weight must be greater than 0.")
else:
  if user_input <= 2:
    rate = 1.1
  elif user_input <= 6:
    rate = 2.2
  elif user_input <= 10:
    rate = 3.7
  else:
    rate = 3.8

print(f"Total shipping charges: ${rate * user_input:.2f}")

"""# (5)	Textbook p153 (5)

The colors red, blue, and yellow are known as the primary colors because they cannot be made by mixing other colors. When you mix two primary colors, you get a secondary color, as shown here:
* When you mix red and blue, you get purple.
* When you mix red and yellow, you get orange.
* When you mix blue and yellow, you get green.

Design a program that prompts the user to enter the names of two primary colors to mix. If the user enters anything other than “red,” “blue,” or “yellow,” the program should display an error message. Otherwise, the program should display the name of the secondary color that results.

* For example (1):
~~~
Please enter the first color: red
Please enter the second color: red
The mixed color is red.
~~~

* For example (2):
~~~
Please enter the first color: red
Please enter the second color: blue
The mixed color is purple.
~~~

* For example (3):
~~~
Please enter the first color: purple
Please enter the second color: blue
The colors you entered are not correct.
~~~
"""

# 作答區(5)
input1 = input("Please enter the first color: ")
input2 = input("Please enter the second color: ")

if input1 == "red" and input2 == "red":
  print("The mixed color is red")
elif input1 == "blue" and input2 == "blue":
    print("The mixed color is blue")
elif input1 == "yellow" and input2 == "yellow":
    print("The mixed color is yellow")
elif (input1 == "blue" and input2 == "red") or (input1 == "red" and input2 == "blue"):
    print("The mixed color is purple")
elif (input1 == "blue" and input2 == "yellow") or (input1 == "yellow" or input2 == "blue"):
    print("The mixed color is green")
elif (input1 == "red" and input2 == "yellow") or (input1 == "yellow" or input2 == "red"):
    print("The mixed color is orange")
else:
    print("The colors you entered are incorrect.")